### ISSUE TITLE
Single date picker with month and year dropdowns

### ISSUE THREAD

**Issue by fadi-gorges** [sersavan/shadcn-calendar-component#1]
This calendar component is great for picking date ranges. I was wondering if you could add the ability to pick just a single date, with the month and year dropdown boxes included, because the original shadcn date picker lacks this. That would be awesome.

**Comment by sersavan** [comment]
@fadi-gorges 

Done, you can try it with props `numberOfMonths={1}`

<img width="695" alt="image" src="https://github.com/sersavan/shadcn-calendar-component/assets/3727722/14e4cb02-faaf-401a-a391-49457f843b7b">

**Comment by fadi-gorges** [comment]
Fantastic work
