### ISSUE TITLE
Not dynamically changing its position based on viewport

### ISSUE THREAD

**Issue by MJUrian-Learner** [sersavan/shadcn-calendar-component#2]
![image](https://github.com/user-attachments/assets/67e43e1a-a090-4aba-9183-66e458ca12cf)

The popover content is not changing its position causing it to overlap if there is no space at the bottom

**Comment by sersavan** [comment]
This was done to make sure the popover appears in a position that doesn't block the component when there isn't enough space at the bottom to ensure the date can be changed using the mouse wheel.
